### ISSUE TITLE
下载svga失败没有抛出错误

### ISSUE THREAD

**Issue by Weeken** [SVGAPlus/SVGAPlus#13]
![image](https://github.com/SVGAPlus/SVGAPlus/assets/18238515/d10cfba4-b3a0-4b78-87dc-31848044f44e)
你应该是在loadSvgaFile的时候没有判断状态码，403没有触发xhr的onerror，然后就返回了arrayBuffer，导致init失败了

**Comment by LancerComet** [comment]
谢谢指出，稍后我看一下，最近比较忙
如果比较急的话可以先自己用 fetch 代替然后再进行错误处理，效果是一样的

**Comment by LancerComet** [comment]
已发布 @svgaplus/core@2.0.2，如果还有问题请您重新 open 此 issue
