### ISSUE TITLE
如何播放多个svga？

### ISSUE THREAD

**Issue by passby6someone** [SVGAPlus/SVGAPlus#6]
您好，我想实现将一个svga动画循环播放多次，然后切换到另一个svga动画，这种场景有什么比较好的方案么？

我参考了您在[v2ex](https://www.v2ex.com/t/701013)上写的介绍，但是我并不是播放一个SVGA中的不同帧，而是播放不同的svga

**Comment by LancerComet** [comment]
这种场景是创建多个 SVGA 后去控制的，而不是在一个 SVGA 上反复卸载并重新初始化
包括我们在公司做活动页的时候，一开始会创建多个 SVGA 的，然后根据业务逻辑去控制

**Comment by passby6someone** [comment]
> 这种场景是创建多个 SVGA 后去控制的，而不是在一个 SVGA 上反复卸载并重新初始化 包括我们在公司做活动页的时候，一开始会创建多个 SVGA 的，然后根据业务逻辑去控制

好的，多谢，我试试
