### ISSUE TITLE
SVGA帧数过多导致动画卡顿

### ISSUE THREAD

**Issue by passby6someone** [SVGAPlus/SVGAPlus#7]
您好，之前说的多个svga问题，因为我的动画比较多，如果准备多个canvas挂载会比较消耗性能，于是把所有动画合成到一个svga中，切换播放哪一段帧

但是带来一个问题，帧数太多导致在 packages/renderer.pixi/lib/index.ts 中的 _drawBitmapSprite 方法调用耗费了太长时间，我并没有对alpha通道，layout以及transform进行设置，find方法遍历消耗了大量性能

![image](https://user-images.githubusercontent.com/43069149/173488806-4ba9226f-46de-44a4-b5e9-1579b5767b40.png)

![image](https://user-images.githubusercontent.com/43069149/173489052-36fecadd-63ff-4111-b1e5-4c40a36f2d58.png)

![image](https://user-images.githubusercontent.com/43069149/173489180-6fcdd19c-34c3-4033-835f-703028a40c2f.png)

我稍后会提个pr修复该问题，如果可以麻烦您检查一下该pr，因为我对pixi的render不是很熟悉😂

**Comment by passby6someone** [comment]
抱歉，我前面理解错了，alpha通道值之类的是SVGA本身会带有的属性，我加上了map数据结构来更快的获取到对应的对象，自测已经能解决动画卡顿问题了

**Comment by LancerComet** [comment]
好的我稍后看看，今天没来得及

**Comment by LancerComet** [comment]
已发布，@svgaplus/renderer.pixi@1.0.3
@passby6someone
